---

- name: Create databases on database servers
  hosts: db_servers
  gather_facts: true
  become: true

  vars_files:
    - secrets.yml

  tasks:
    - name: Create new database on servers
      community.general.mssql_db:
        login_host: "{{ mssql_host }}"
        login_user: "{{ mssql_user }}"
        login_password: "{{ mssql_pass }}"
        name: "{{ db_name  | default('aap-test-db') }}"
        state: present
